# Generated by Django 2.0 on 2017-12-17 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('content', models.CharField(max_length=45)),
                ('case_status', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('priority', models.CharField(max_length=45)),
                ('template', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='documentType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='akager.DocumentType'),
        ),
        migrations.AddField(
            model_name='document',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='akager.Resident'),
        ),
        migrations.AddField(
            model_name='document',
            name='staffMember',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='akager.StaffMember'),
        ),
    ]
